name: Scraper Diário
on:
  workflow_dispatch:
  schedule:
    - cron: '0 11 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Dá permissão de escrita explicitamente
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: pip install -r requirements.txt
      - run: python scraper_vv.py
      - name: Salvar e Enviar Arquivos
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add noticias_vv.csv feed_vila_velha_vv.xml
          git commit -m "Atualização de dados" || echo "Sem mudanças"
          git push
